### ISSUE TITLE
Cannot make this works with elasticsearch

### ISSUE THREAD

**Issue by jsirex** [logstash/log4j-jsonevent-layout#28]
I want to plug elasticsearch logs into logstash, but it doesn't work.

I'm not sure is it a bug or configuration issue.
1. I've installed elasticsearch 0.90.5
2. Put jsonevent-layout-1.4.jar into ES lib directory
3. I've changed logging.yml appender -> file section like this:

```
  file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}.log
    datePattern: "'.'yyyy-MM-dd"   
    layout:
      type: net.logstash.log4j.JSONEventLayout
```
1. removed logs and Restarted elasticsearch.

Result: no logs, even no file ${path.logs}/${cluster.name}.log
